title: <p align="center"> Peggy Lee </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  
  <p align="justify">
  After acquiring experience in medical laboratory science and healthcare software development, I achieved MS degree in Information Science at School of Information, University of Arizona.
  <br><br>
  My goal is to conceptualize medical science, artiÔ¨Åcial intelligence, software engineering, and information technology.
  <br><br>
  </p>
  
google_analytics: UA-145578661-1 # Google Analytics tracking ID
